export enum ActionTypes {
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_AT_CART = 'REMOVE_AT_CART',
    SET_PAYMENT = 'SET_PAYMENT',
    SET_ADRESS = 'SET_ADRESS',
    CAlCULATE_TOTAL = 'CAlCULATE_TOTAL',
}